### ISSUE TITLE
You have no right to counterfeit.

### ISSUE THREAD

**Issue by ponsinsun** [fossilet/4digits#9]
不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利不准盜用發明人的權利

**Comment by ponsinsun** [comment]
發明人有要求，請你立下但書。或者撤除。
請先把遊戲名稱改為1A2B。
你從來不是台灣人，也不是新莊丹鳳國小的同學。更不姓彭。
所以你只是抄襲發明人，我：彭新舜本人。
你有兩個選擇：
１，跟著我的意思寫入Windows Games 並改名為 1A2B。再由我主筆寫好 wikipedia介紹。
２，刪除此抄襲遊戲程式。你不是丹鳳國小畢業，沒有資格，也從來不是台灣人，也從來不是發明人。
我建議你選擇第一選項。我自己會寫，用不著你改我的名稱。 1A2B Sweeper. 你寫得來嗎？ 菜鳥，你無意間冒犯了發明人。

**Comment by fossilet** [comment]
🐸
